# Microsoft Intern Engage 2022

In [1]:
import pandas as pd
import numpy as np

## Extracting features of 2018 movies from Wikipedia

In [2]:
# there is no sufficient data on kaggle for movies after 2017 , so we are extracting the data from wikipidea
# there are 4 tables , so we just collected them into a single-single dataframe

link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [3]:
# appending all the dataframes into a single dataframe
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [4]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],NaN
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN
...,...,...,...,...,...,...,...
267,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,NaN,[164]
268,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,NaN,[137]
269,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,NaN,[228]
270,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",NaN,[260]
271,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,NaN,[261]

In [5]:
# we are using this tmdbv3api , because we are going to extract the data from TMDB based on the MOVIE id
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\hp\anaconda3\lib\site-packages (1.7.6)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (from tmdbv3api) (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (2022.5.18.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.0.4)

In [6]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = 'cd109cb98c90d3020a252e6f524b8d63'      # this is API key (this is unique)

In [7]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_movie_id(x):
    try:
        result = tmdb_movie.search(x)
        return result[0].id
    except:
        return np.NaN

In [8]:
# based on the movie title , storing the id for movie
df['id'] = df['Title'].map(lambda x: get_movie_id(str(x)))

In [9]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_movie_avg_vt(x):
    try:
        result = tmdb_movie.search(x)
        return result[0].vote_average
    except:
        return np.NaN

In [11]:
df['vote_average'] = df['Title'].map(lambda x: get_movie_avg_vt(str(x)))

In [12]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_movie_vt_cnt(x):
    try:
        result = tmdb_movie.search(x)
        return result[0].vote_count
    except:
        return np.NaN

In [13]:
df['vote_count'] = df['Title'].map(lambda x: get_movie_vt_cnt(str(x)))

In [14]:
# by the use of this function , we are extracting the movie related information based on their movie ID with the help of API KEY

from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [15]:
# based on the movie title , storing the geners for movie
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [16]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,id,vote_average,vote_count,genres
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN,406563,6.2,2241,Horror Mystery Thriller
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN,426258,5.5,62,Thriller Drama
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],NaN,348389,5.0,176,Action Thriller
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN,468210,6.5,137,Drama History Western
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN,399035,6.3,3760,Action Thriller Mystery
...,...,...,...,...,...,...,...,...,...,...,...
267,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,NaN,[164],426563,4.3,669,Mystery Adventure Comedy Crime
268,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,NaN,[137],307663,4.4,474,Thriller Science Fiction Action Adventure
269,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,NaN,[228],339380,7.4,828,Drama History
270,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",NaN,[260],471507,5.9,573,Thriller Crime Drama Action
271,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,NaN,[261],569547,6.8,3318,Science Fiction Mystery Drama Thriller TV Movie

In [17]:
# these are the important columns for the 2018 movies data
df_2018 = df[['id','Title','Cast and crew','genres','vote_count','vote_average']]

In [18]:
df_2018

,id,Title,Cast and crew,genres,vote_count,vote_average
0,406563,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,2241,6.2
1,426258,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,62,5.5
2,348389,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,176,5.0
3,468210,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Drama History Western,137,6.5
4,399035,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,3760,6.3
...,...,...,...,...,...,...
267,426563,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,669,4.3
268,307663,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,474,4.4
269,339380,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,828,7.4
270,471507,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,573,5.9
271,569547,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,3318,6.8

In [19]:
# extracting movie director name 
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [20]:
df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [21]:
# extracting movie actror1 name 
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [22]:
df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
# extracting movie actror2 name 
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [24]:
df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
# extracting movie actror3 name 
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [26]:
df_2018['actor_3_name'] = df_2018['Cast and crew'].map(lambda x: get_actor3(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [27]:
df_2018

,id,Title,Cast and crew,genres,vote_count,vote_average,director_name,actor_1_name,actor_2_name,actor_3_name
0,406563,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,2241,6.2,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,426258,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,62,5.5,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,348389,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,176,5.0,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,468210,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Drama History Western,137,6.5,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,399035,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,3760,6.3,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson
...,...,...,...,...,...,...,...,...,...,...
267,426563,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,669,4.3,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
268,307663,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,474,4.4,Adam McKay,Christian Bale,Amy Adams,Steve Carell
269,339380,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,828,7.4,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
270,471507,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,573,5.9,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
271,569547,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,3318,6.8,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [28]:
df_2018 = df_2018.rename(columns={'Title':'movie_title'})

In [31]:
# just taking the important columns for further process
new_df18 = df_2018.loc[:,['id','director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title','vote_count','vote_average']]

In [32]:
new_df18

,id,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,vote_count,vote_average
0,406563,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,Insidious: The Last Key,2241,6.2
1,426258,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,The Strange Ones,62,5.5
2,348389,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,Stratton,176,5.0
3,468210,Warwick Thornton,Bryan Brown,Sam Neill,NaN,Drama History Western,Sweet Country,137,6.5
4,399035,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,The Commuter,3760,6.3
...,...,...,...,...,...,...,...,...,...
267,426563,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,Holmes & Watson,669,4.3
268,307663,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,Vice,474,4.4
269,339380,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,On the Basis of Sex,828,7.4
270,471507,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,Destroyer,573,5.9
271,569547,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,Black Mirror: Bandersnatch,3318,6.8

In [33]:
# replacing the null values with the unknown
new_df18['actor_2_name'] = new_df18['actor_2_name'].replace(np.nan, 'unknown')
new_df18['actor_3_name'] = new_df18['actor_3_name'].replace(np.nan, 'unknown')

In [34]:
new_df18['movie_title'] = new_df18['movie_title'].str.lower()

In [35]:
# making a new column and Concatenate all the columns into that single column
new_df18['comb'] = new_df18['actor_1_name'] + ' ' + new_df18['actor_2_name'] + ' '+ new_df18['actor_3_name'] + ' '+ new_df18['director_name'] +' ' + new_df18['genres']

In [36]:
# this is the final data for 2018 that is having all the important information
new_df18

,id,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,vote_count,vote_average,comb
0,406563,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,2241,6.2,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,426258,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,62,5.5,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,348389,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,176,5.0,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,468210,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,sweet country,137,6.5,Bryan Brown Sam Neill unknown Warwick Thornton...
4,399035,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,the commuter,3760,6.3,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...,...,...,...
267,426563,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,holmes & watson,669,4.3,Will Ferrell John C. Reilly Rebecca Hall Etan ...
268,307663,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,vice,474,4.4,Christian Bale Amy Adams Steve Carell Adam McK...
269,339380,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,on the basis of sex,828,7.4,Felicity Jones Armie Hammer Justin Theroux Mim...
270,471507,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,destroyer,573,5.9,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
271,569547,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,black mirror: bandersnatch,3318,6.8,Fionn Whitehead Will Poulter Asim Chaudhry Dav...

## Extracting features of 2019 movies from Wikipedia

### doing the same thing that we have did for 2018 data , just change the 2018 data link with 2019 data

In [37]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [38]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [39]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
237,DECEMBER,25,Spies in Disguise,20th Century Fox / Blue Sky Studios / Chernin ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[132]
238,DECEMBER,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[221]
239,DECEMBER,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[222]
240,DECEMBER,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[223]
241,DECEMBER,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[224]

In [41]:
df['id'] = df['Title'].map(lambda x: get_movie_id(str(x)))

In [42]:
df['vote_count'] = df['Title'].map(lambda x: get_movie_vt_cnt(str(x)))

In [43]:
df['vote_average'] = df['Title'].map(lambda x: get_movie_avg_vt(str(x)))

In [44]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [45]:
df_2019 = df[['id','Title','Cast and crew','genres','vote_count','vote_average']]

In [46]:
df_2019

,id,Title,Cast and crew,genres,vote_count,vote_average
0,522681,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...",Horror Thriller Mystery,3766,6.5
1,561362,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,Thriller Drama,227,6.4
2,567738,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller,112,6.1
3,508763,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,Drama Adventure Family,886,7.3
4,440472,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,Comedy Drama,962,7.1
...,...,...,...,...,...,...
237,431693,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Animation Action Adventure Comedy Family,2280,7.7
238,331482,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama Romance,4815,7.9
239,530915,1917,Sam Mendes (director/screenplay); Krysty Wilso...,War Drama Action Thriller,9750,8.0
240,522212,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama Crime History,1714,8.0
241,565307,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama,68,6.6

In [47]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [48]:
df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [49]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [50]:
df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [51]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [52]:
df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [53]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [54]:
df_2019['actor_3_name'] = df_2019['Cast and crew'].map(lambda x: get_actor3(x))

In [55]:
df_2019 = df_2019.rename(columns={'Title':'movie_title'})

In [56]:
new_df19 = df_2019.loc[:,['id','director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title','vote_count','vote_average']]

In [57]:
new_df19['actor_2_name'] = new_df19['actor_2_name'].replace(np.nan, 'unknown')
new_df19['actor_3_name'] = new_df19['actor_3_name'].replace(np.nan, 'unknown')

In [58]:
new_df19['movie_title'] = new_df19['movie_title'].str.lower()

In [59]:
new_df19['comb'] = new_df19['actor_1_name'] + ' ' + new_df19['actor_2_name'] + ' '+ new_df19['actor_3_name'] + ' '+ new_df19['director_name'] +' ' + new_df19['genres']

In [60]:
new_df19

,id,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,vote_count,vote_average,comb
0,522681,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,Horror Thriller Mystery,escape room,3766,6.5,Taylor Russell Logan Miller Deborah Ann Woll A...
1,561362,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,Thriller Drama,rust creek,227,6.4,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,567738,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,112,6.1,Donald Sutherland Vincent Kartheiser Oliver De...
3,508763,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,Drama Adventure Family,a dog's way home,886,7.3,Bryce Dallas Howard Edward James Olmos Alexand...
4,440472,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,Comedy Drama,the upside,962,7.1,Bryan Cranston Kevin Hart Nicole Kidman Neil B...
...,...,...,...,...,...,...,...,...,...,...
237,431693,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,2280,7.7,Will Smith Tom Holland Rashida Jones Nick Brun...
238,331482,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,4815,7.9,Saoirse Ronan Emma Watson Florence Pugh Greta ...
239,530915,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,9750,8.0,George MacKay Dean-Charles Chapman Mark Strong...
240,522212,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,1714,8.0,Michael B. Jordan Jamie Foxx Brie Larson Desti...
241,565307,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,68,6.6,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [61]:
# appending the 2018 & 2019 movie data into a single dataframe
my_df = new_df18.append(new_df19,ignore_index=True)

In [62]:
my_df

,id,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,vote_count,vote_average,comb
0,406563,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,2241,6.2,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,426258,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,62,5.5,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,348389,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,176,5.0,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,468210,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,sweet country,137,6.5,Bryan Brown Sam Neill unknown Warwick Thornton...
4,399035,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,the commuter,3760,6.3,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...,...,...,...
509,431693,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,2280,7.7,Will Smith Tom Holland Rashida Jones Nick Brun...
510,331482,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,4815,7.9,Saoirse Ronan Emma Watson Florence Pugh Greta ...
511,530915,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,9750,8.0,George MacKay Dean-Charles Chapman Mark Strong...
512,522212,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,1714,8.0,Michael B. Jordan Jamie Foxx Brie Larson Desti...
513,565307,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,68,6.6,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [63]:
# this is old data (till 2017)
old_df = pd.read_csv('data17.csv')

In [64]:
old_df

,id,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,vote_count,vote_average,comb
0,19995,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Action Adventure Fantasy Sci-Fi,avatar,11800,7.2,Sam Worthington Zoe Saldana Sigourney Weaver J...
1,285,Gore Verbinski,Johnny Depp,Orlando Bloom,Keira Knightley,Adventure Fantasy Action,pirates of the caribbean: at world's end,4500,6.9,Johnny Depp Orlando Bloom Keira Knightley Gore...
2,206647,Sam Mendes,Daniel Craig,Christoph Waltz,LÃ©a Seydoux,Action Adventure Crime,spectre,4466,6.3,Daniel Craig Christoph Waltz LÃ©a Seydoux Sam M...
3,49026,Christopher Nolan,Christian Bale,Michael Caine,Gary Oldman,Action Crime Drama Thriller,the dark knight rises,9106,7.6,Christian Bale Michael Caine Gary Oldman Chris...
4,49529,Andrew Stanton,Taylor Kitsch,Lynn Collins,Samantha Morton,Action Adventure Sci-Fi,john carter,2124,6.1,Taylor Kitsch Lynn Collins Samantha Morton And...
...,...,...,...,...,...,...,...,...,...,...
4553,14337,Shane Carruth,Shane Carruth,David Sullivan,Casey Gooden,Sci-Fi Drama Thriller,primer,658,6.9,Shane Carruth David Sullivan Casey Gooden Shan...
4554,9367,Robert Rodriguez,Carlos Gallardo,Jaime de Hoyos,Peter Marquardt,Action Crime Thriller,el mariachi,238,6.6,Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4555,72766,Edward Burns,Edward Burns,Kerry BishÃ©,Marsha Dietlein,Comedy Romance,newlyweds,5,5.9,Edward Burns Kerry BishÃ© Marsha Dietlein Edwar...
4556,231617,Scott Smith,Eric Mabius,Kristin Booth,Crystal Lowe,Comedy Drama Romance TV Movie,"signed, sealed, delivered",6,7.0,Eric Mabius Kristin Booth Crystal Lowe Scott S...
4557,25975,Brian Herzlinger Jon Gunn Brett Winn,Drew Barrymore,Brian Herzlinger,Corey Feldman,Documentary,my date with drew,16,6.3,Drew Barrymore Brian Herzlinger Corey Feldman ...

In [65]:
# merging the current (2018 & 2019) data with old (till 2017) data 
final_df = old_df.append(my_df,ignore_index=True)

In [66]:
final_df

,id,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,vote_count,vote_average,comb
0,19995,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Action Adventure Fantasy Sci-Fi,avatar,11800,7.2,Sam Worthington Zoe Saldana Sigourney Weaver J...
1,285,Gore Verbinski,Johnny Depp,Orlando Bloom,Keira Knightley,Adventure Fantasy Action,pirates of the caribbean: at world's end,4500,6.9,Johnny Depp Orlando Bloom Keira Knightley Gore...
2,206647,Sam Mendes,Daniel Craig,Christoph Waltz,LÃ©a Seydoux,Action Adventure Crime,spectre,4466,6.3,Daniel Craig Christoph Waltz LÃ©a Seydoux Sam M...
3,49026,Christopher Nolan,Christian Bale,Michael Caine,Gary Oldman,Action Crime Drama Thriller,the dark knight rises,9106,7.6,Christian Bale Michael Caine Gary Oldman Chris...
4,49529,Andrew Stanton,Taylor Kitsch,Lynn Collins,Samantha Morton,Action Adventure Sci-Fi,john carter,2124,6.1,Taylor Kitsch Lynn Collins Samantha Morton And...
...,...,...,...,...,...,...,...,...,...,...
5067,431693,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,2280,7.7,Will Smith Tom Holland Rashida Jones Nick Brun...
5068,331482,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,4815,7.9,Saoirse Ronan Emma Watson Florence Pugh Greta ...
5069,530915,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,9750,8.0,George MacKay Dean-Charles Chapman Mark Strong...
5070,522212,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,1714,8.0,Michael B. Jordan Jamie Foxx Brie Larson Desti...
5071,565307,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,68,6.6,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [67]:
final_df.isna().sum()

id               0
director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           2
movie_title      0
vote_count       0
vote_average     0
comb             2
dtype: int64

In [68]:
final_df = final_df.dropna(how='any')

In [69]:
final_df.isna().sum()

id               0
director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
vote_count       0
vote_average     0
comb             0
dtype: int64

In [70]:
# storing the data (till 2019) into a csv file
final_df.to_csv('data19.csv',index=False)